-- テーブルが重複しないよう存在チェック、あれば削除します
DROP TABLE IF EXISTS QUESTION_DATA;

-- 質問一覧テーブル
CREATE TABLE `QUESTION_DATA` (
  `QUESTION_DATA_ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `QUESTION_NAME` VARCHAR(64) NOT NULL,
  `QUESTION_STATEMENT` VARCHAR(256) NOT NULL,
  `TAG_MASTER_ID` int(10) NOT NULL,
  `QUESTION_TYPE_ID` int(10) NOT NULL,
  `USER_ID` INT (10) NOT NULL,
      `CREATE_DATE` DATETIME  DEFAULT current_timestamp,
  `UPDATE_DATE` DATETIME,
  PRIMARY KEY (`QUESTION_DATA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
