-- テーブルが重複しないよう存在チェック、あれば削除します
DROP TABLE IF EXISTS QUESTION_TYPE;

-- 問題タイプテーブル
CREATE TABLE `QUESTION_TYPE` (
  `QUESTION_TYPE_ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `QUESTION_TYPE` VARCHAR(64)  NOT NULL,
  PRIMARY KEY (`QUESTION_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
