-- テーブルが重複しないよう存在チェック、あれば削除します
DROP TABLE IF EXISTS QUESTION_TAG;

-- 問題タイプテーブル
CREATE TABLE `QUESTION_TAG` (
  `QUESTION_TAG_ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `QUESTION_TAG` VARCHAR(64)  NOT NULL,
  PRIMARY KEY (`QUESTION_TAG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
