-- テーブルが重複しないよう存在チェック、あれば削除します
DROP TABLE IF EXISTS QUESTION_DETAIL_DATA;

-- 質問詳細テーブル
CREATE TABLE `QUESTION_DETAIL_DATA` (
  `QUESTION_DETAIL_DATA_ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `QUESTION_DATA_ID` bigint unsigned NOT NULL,
  `ANSWER_STATEMENT` VARCHAR(256) NOT NULL,
  `CORRECT_FLAG` int(1) NOT NULL,
  PRIMARY KEY (`QUESTION_DETAIL_DATA_ID`),
  FOREIGN KEY (`QUESTION_DATA_ID`) REFERENCES `QUESTION_DATA` (`QUESTION_DATA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
